# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Levi Segal"
license = "MIT"
licenselink = "https://github.com/levisegal/hugo-photo-gallery.git/LICENSE.md"
description = "Photo Gallery theme for websites built with hugo"
homepage = "https://github.com/levisegal/hugo-photo-gallery"
tags = ["photography", "hugo", "hugo-theme"]
features = ["gallery"]
min_version = 0.1

[author]
    name = "Levi Segal"
    homepage = "https://github.com/levisegal/"